/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.core.bncs;

/**
 * @author scotta
 */
public enum BNCSChatEventId {
	EID_UNKNOWN_0x00,
	EID_SHOWUSER,
	EID_JOIN,
	EID_LEAVE,
	EID_WHISPER,
	EID_TALK,
	EID_BROADCAST,
	EID_CHANNEL,
	EID_UNKNOWN_0x08,
	EID_USERFLAGS,
	EID_WHISPERSENT,
	EID_UNKNOWN_0x0B,
	EID_UNKNOWN_0x0C,
	EID_CHANNELFULL,
	EID_CHANNELDOESNOTEXIST,
	EID_CHANNELRESTRICTED,
	EID_UNKNOWN_0x10,
	EID_UNKNOWN_0x11,
	EID_INFO,
	EID_ERROR,
	EID_UNKNOWN_0x14,
	EID_UNKNOWN_0x15,
	EID_UNKNOWN_0x16,
	EID_EMOTE,
}
