/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.core.botnet;

public enum BotNetPacketId {
	PACKET_IDLE,
	PACKET_LOGON,
	PACKET_STATSUPDATE,
	PACKET_DATABASE,
	PACKET_MESSAGE,
	PACKET_CYCLE,
	PACKET_USERINFO,
	PACKET_USERLOGGINGOFF,
	PACKET_COMMAND,
	PACKET_CHANGEDBPASSWORDRAW,
	PACKET_BOTNETVERSIONRAW,
	PACKET_BOTNETCHATRAW,
	PACKET_ACCOUNTRAW,
	PACKET_CHATDROPOPTIONSRAW
}
