/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.core.digitaltext;

import net.bnubot.core._super._PacketId;

/**
 * @author scotta
 */
public enum DTPacketId implements _PacketId<DTConnection> {
	PKT_UNKNOWN_0x00,
	PKT_LOGON,
	PKT_ENTERCHANNEL,
	PKT_UNKNOWN_0x03,
	PKT_UNKNOWN_0x04,
	PKT_UNKNOWN_0x05,
	PKT_UNKNOWN_0x06,
	PKT_UNKNOWN_0x07,
	PKT_UNKNOWN_0x08,
	PKT_UNKNOWN_0x09,
	PKT_UNKNOWN_0x0A,
	PKT_UNKNOWN_0x0B,
	PKT_UNKNOWN_0x0C,
	PKT_UNKNOWN_0x0D,
	PKT_UNKNOWN_0x0E,
	PKT_UNKNOWN_0x0F,
	PKT_UNKNOWN_0x10,
	PKT_UNKNOWN_0x11,
	PKT_CHANNELUSERS,
	PKT_CHANNELJOIN,
	PKT_CHANNELLEAVE,
	PKT_CHANNELCHAT,
	PKT_UNKNOWN_0x16,
	PKT_UNKNOWN_0x17,
	PKT_UNKNOWN_0x18,
	PKT_UNKNOWN_0x19,
	PKT_UNKNOWN_0x1A,
	PKT_UNKNOWN_0x1B,
	PKT_UNKNOWN_0x1C,
	PKT_UNKNOWN_0x1D,
	PKT_UNKNOWN_0x1E,
	PKT_UNKNOWN_0x1F,
	PKT_USERUPDATE,
	PKT_UNKNOWN_0x21,
	PKT_UNKNOWN_0x22,
	PKT_UNKNOWN_0x23,
	PKT_UNKNOWN_0x24,
	PKT_UNKNOWN_0x25,
	PKT_UNKNOWN_0x26,
	PKT_UNKNOWN_0x27,
	PKT_UNKNOWN_0x28,
	PKT_UNKNOWN_0x29,
	PKT_UNKNOWN_0x2A,
	PKT_UNKNOWN_0x2B,
	PKT_UNKNOWN_0x2C,
	PKT_UNKNOWN_0x2D,
	PKT_UNKNOWN_0x2E,
	PKT_UNKNOWN_0x30,
	PKT_NULL,
}
