/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.db.auto;

import net.bnubot.db.Command;
import net.bnubot.db.CustomDataObject;

/**
 * Class _CommandAlias was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 * @author cayenne-generated-file
 */
@SuppressWarnings("serial")
public abstract class _CommandAlias extends CustomDataObject<String> {
    public static final String ALIAS_PROPERTY = "alias";
    public static final String TO_COMMAND_PROPERTY = "toCommand";

    public static final String ALIAS_PK_COLUMN = "alias";

    public void setAlias(String alias) {
        writeProperty(ALIAS_PROPERTY, alias);
    }
    public String getAlias() {
        return (String)readProperty(ALIAS_PROPERTY);
    }

    public void setToCommand(Command toCommand) {
        setToOneTarget(TO_COMMAND_PROPERTY, toCommand, true);
    }

    public Command getToCommand() {
        return (Command)readProperty(TO_COMMAND_PROPERTY);
    }
}
