package net.bnubot.db.auto;

import java.util.Date;

import net.bnubot.db.Account;
import net.bnubot.db.CustomDataObject;

/**
 * Class _Mail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Mail extends CustomDataObject {

    public static final String ISREAD_PROPERTY = "isread";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String SENT_PROPERTY = "sent";
    public static final String SENT_FROM_PROPERTY = "sentFrom";
    public static final String SENT_TO_PROPERTY = "sentTo";

    public static final String ID_PK_COLUMN = "id";

    public void setIsread(boolean isread) {
        writeProperty("isread", isread);
    }
	public boolean isIsread() {
        Boolean value = (Boolean)readProperty("isread");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }

    public void setSent(Date sent) {
        writeProperty("sent", sent);
    }
    public Date getSent() {
        return (Date)readProperty("sent");
    }

    public void setSentFrom(Account sentFrom) {
        setToOneTarget("sentFrom", sentFrom, true);
    }

    public Account getSentFrom() {
        return (Account)readProperty("sentFrom");
    }


    public void setSentTo(Account sentTo) {
        setToOneTarget("sentTo", sentTo, true);
    }

    public Account getSentTo() {
        return (Account)readProperty("sentTo");
    }


}
