/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.db.auto;

import java.util.Date;

import net.bnubot.db.Account;
import net.bnubot.db.CustomDataObject;

/**
 * Class _Mail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 * @author cayenne-generated-file
 */
@SuppressWarnings("serial")
public abstract class _Mail extends CustomDataObject<Integer> {
    public static final String ISREAD_PROPERTY = "isread";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String SENT_PROPERTY = "sent";
    public static final String SENT_FROM_PROPERTY = "sentFrom";
    public static final String SENT_TO_PROPERTY = "sentTo";

    public static final String ID_PK_COLUMN = "id";

    public void setIsread(boolean isread) {
        writeProperty(ISREAD_PROPERTY, isread);
    }
	public boolean isIsread() {
        Boolean value = (Boolean)readProperty(ISREAD_PROPERTY);
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMessage(String message) {
        writeProperty(MESSAGE_PROPERTY, message);
    }
    public String getMessage() {
        return (String)readProperty(MESSAGE_PROPERTY);
    }

    public void setSent(Date sent) {
        writeProperty(SENT_PROPERTY, sent);
    }
    public Date getSent() {
        return (Date)readProperty(SENT_PROPERTY);
    }

    public void setSentFrom(Account sentFrom) {
        setToOneTarget(SENT_FROM_PROPERTY, sentFrom, true);
    }

    public Account getSentFrom() {
        return (Account)readProperty(SENT_FROM_PROPERTY);
    }


    public void setSentTo(Account sentTo) {
        setToOneTarget(SENT_TO_PROPERTY, sentTo, true);
    }

    public Account getSentTo() {
        return (Account)readProperty(SENT_TO_PROPERTY);
    }
}
