/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.db.auto;

import java.util.Date;
import java.util.List;

import net.bnubot.db.Account;
import net.bnubot.db.BNLogin;
import net.bnubot.db.CustomDataObject;
import net.bnubot.db.Mail;
import net.bnubot.db.Rank;

/**
 * Class _Account was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 * @author cayenne-generated-file
 */
@SuppressWarnings("serial")
public abstract class _Account extends CustomDataObject {

    public static final String BIRTHDAY_PROPERTY = "birthday";
    public static final String CREATED_PROPERTY = "created";
    public static final String LAST_RANK_CHANGE_PROPERTY = "lastRankChange";
    public static final String NAME_PROPERTY = "name";
    public static final String TRIVIA_CORRECT_PROPERTY = "triviaCorrect";
    public static final String TRIVIA_WIN_PROPERTY = "triviaWin";
    public static final String BN_LOGINS_PROPERTY = "bnLogins";
    public static final String RANK_PROPERTY = "rank";
    public static final String RECIEVED_MAIL_PROPERTY = "recievedMail";
    public static final String RECRUITER_PROPERTY = "recruiter";
    public static final String RECRUITS_PROPERTY = "recruits";
    public static final String SENT_MAIL_PROPERTY = "sentMail";

    public static final String ID_PK_COLUMN = "id";

    public void setBirthday(Date birthday) {
        writeProperty("birthday", birthday);
    }
    public Date getBirthday() {
        return (Date)readProperty("birthday");
    }

    public void setCreated(Date created) {
        writeProperty("created", created);
    }
    public Date getCreated() {
        return (Date)readProperty("created");
    }

    public void setLastRankChange(Date lastRankChange) {
        writeProperty("lastRankChange", lastRankChange);
    }
    public Date getLastRankChange() {
        return (Date)readProperty("lastRankChange");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setTriviaCorrect(int triviaCorrect) {
        writeProperty("triviaCorrect", triviaCorrect);
    }
    public int getTriviaCorrect() {
        Object value = readProperty("triviaCorrect");
        return (value != null) ? (Integer) value : 0;
    }

    public void setTriviaWin(int triviaWin) {
        writeProperty("triviaWin", triviaWin);
    }
    public int getTriviaWin() {
        Object value = readProperty("triviaWin");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToBnLogins(BNLogin obj) {
        addToManyTarget("bnLogins", obj, true);
    }
    public void removeFromBnLogins(BNLogin obj) {
        removeToManyTarget("bnLogins", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BNLogin> getBnLogins() {
        return (List<BNLogin>)readProperty("bnLogins");
    }


    public void setRank(Rank rank) {
        setToOneTarget("rank", rank, true);
    }

    public Rank getRank() {
        return (Rank)readProperty("rank");
    }


    public void addToRecievedMail(Mail obj) {
        addToManyTarget("recievedMail", obj, true);
    }
    public void removeFromRecievedMail(Mail obj) {
        removeToManyTarget("recievedMail", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Mail> getRecievedMail() {
        return (List<Mail>)readProperty("recievedMail");
    }


    public void setRecruiter(Account recruiter) {
        setToOneTarget("recruiter", recruiter, true);
    }

    public Account getRecruiter() {
        return (Account)readProperty("recruiter");
    }


    public void addToRecruits(Account obj) {
        addToManyTarget("recruits", obj, true);
    }
    public void removeFromRecruits(Account obj) {
        removeToManyTarget("recruits", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Account> getRecruits() {
        return (List<Account>)readProperty("recruits");
    }


    public void addToSentMail(Mail obj) {
        addToManyTarget("sentMail", obj, true);
    }
    public void removeFromSentMail(Mail obj) {
        removeToManyTarget("sentMail", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Mail> getSentMail() {
        return (List<Mail>)readProperty("sentMail");
    }


}
