/**
 * This file is distributed under the GPL
 * $Id$
 */

package net.bnubot.db.auto;

import java.util.Date;

import net.bnubot.db.Account;
import net.bnubot.db.CustomDataObject;

/**
 * Class _BNLogin was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 * @author cayenne-generated-file
 */
@SuppressWarnings("serial")
public abstract class _BNLogin extends CustomDataObject<String> {
    public static final String CREATED_PROPERTY = "created";
    public static final String LAST_ACTION_PROPERTY = "lastAction";
    public static final String LAST_SEEN_PROPERTY = "lastSeen";
    public static final String LEVEL_D2_PROPERTY = "levelD2";
    public static final String LEVEL_W3_PROPERTY = "levelW3";
    public static final String LOGIN_PROPERTY = "login";
    public static final String WINS_SEXP_PROPERTY = "winsSEXP";
    public static final String WINS_STAR_PROPERTY = "winsSTAR";
    public static final String WINS_W2BN_PROPERTY = "winsW2BN";
    public static final String ACCOUNT_PROPERTY = "account";

    public static final String ID_PK_COLUMN = "id";

    public void setCreated(Date created) {
        writeProperty(CREATED_PROPERTY, created);
    }
    public Date getCreated() {
        return (Date)readProperty(CREATED_PROPERTY);
    }

    public void setLastAction(String lastAction) {
        writeProperty(LAST_ACTION_PROPERTY, lastAction);
    }
    public String getLastAction() {
        return (String)readProperty(LAST_ACTION_PROPERTY);
    }

    public void setLastSeen(Date lastSeen) {
        writeProperty(LAST_SEEN_PROPERTY, lastSeen);
    }
    public Date getLastSeen() {
        return (Date)readProperty(LAST_SEEN_PROPERTY);
    }

    public void setLevelD2(Integer levelD2) {
        writeProperty(LEVEL_D2_PROPERTY, levelD2);
    }
    public Integer getLevelD2() {
        return (Integer)readProperty(LEVEL_D2_PROPERTY);
    }

    public void setLevelW3(Integer levelW3) {
        writeProperty(LEVEL_W3_PROPERTY, levelW3);
    }
    public Integer getLevelW3() {
        return (Integer)readProperty(LEVEL_W3_PROPERTY);
    }

    public void setLogin(String login) {
        writeProperty(LOGIN_PROPERTY, login);
    }
    public String getLogin() {
        return (String)readProperty(LOGIN_PROPERTY);
    }

    public void setWinsSEXP(Integer winsSEXP) {
        writeProperty(WINS_SEXP_PROPERTY, winsSEXP);
    }
    public Integer getWinsSEXP() {
        return (Integer)readProperty(WINS_SEXP_PROPERTY);
    }

    public void setWinsSTAR(Integer winsSTAR) {
        writeProperty(WINS_STAR_PROPERTY, winsSTAR);
    }
    public Integer getWinsSTAR() {
        return (Integer)readProperty(WINS_STAR_PROPERTY);
    }

    public void setWinsW2BN(Integer winsW2BN) {
        writeProperty(WINS_W2BN_PROPERTY, winsW2BN);
    }
    public Integer getWinsW2BN() {
        return (Integer)readProperty(WINS_W2BN_PROPERTY);
    }

    public void setAccount(Account account) {
        setToOneTarget(ACCOUNT_PROPERTY, account, true);
    }

    public Account getAccount() {
        return (Account)readProperty(ACCOUNT_PROPERTY);
    }
}
