package net.bnubot.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import net.bnubot.db.CommandAlias;

/**
 * Class _Command was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Command extends CayenneDataObject {

    public static final String ACCESS_PROPERTY = "access";
    public static final String CMDGROUP_PROPERTY = "cmdgroup";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String RUNTIME_RELATIONSHIP0_PROPERTY = "runtimeRelationship0";

    public static final String ID_PK_COLUMN = "id";

    public void setAccess(Integer access) {
        writeProperty("access", access);
    }
    public Integer getAccess() {
        return (Integer)readProperty("access");
    }

    public void setCmdgroup(String cmdgroup) {
        writeProperty("cmdgroup", cmdgroup);
    }
    public String getCmdgroup() {
        return (String)readProperty("cmdgroup");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToRuntimeRelationship0(CommandAlias obj) {
        addToManyTarget("runtimeRelationship0", obj, true);
    }
    public void removeFromRuntimeRelationship0(CommandAlias obj) {
        removeToManyTarget("runtimeRelationship0", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CommandAlias> getRuntimeRelationship0() {
        return (List<CommandAlias>)readProperty("runtimeRelationship0");
    }


}
